# See http://www.appveyor.com/docs/appveyor-yml for reference

#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  NUGET_VERSION: 1.2.5
  NUGET_FILE: BosunReporter\BosunReporter.nuspec
  ASSEMBLY_FILE: BosunReporter\Properties\AssemblyInfo.cs

version: $(nuget_version).{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2015 CTP 6

assembly_info:
  patch: true
  file: $(ASSEMBLY_FILE)
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  project: BosunReporter\BosunReporter.csproj
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal

before_build:
  - ps: Scripts\SetNugetVersion.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#



#---------------------------------#
#      artifacts configuration    #
#---------------------------------#



#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: gbdN6iXbtLTk1MiBecxRJvdoc6fR6x4AEFAQNuZ+UMR9NvQnXW12PXfd16gtGVGp
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

  # for pre-release versions
  - provider: NuGet
    api_key:
      secure: NiH62CvEa6ztPGnR9glvKexCL5sJStB62JcJ/8CcVJJAj7rkCzZvfN87E5xPpNd0
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      branch: master

  # for release versions
  - provider: NuGet
    api_key:
      secure: NiH62CvEa6ztPGnR9glvKexCL5sJStB62JcJ/8CcVJJAj7rkCzZvfN87E5xPpNd0
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true

